global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          group: 'prom'

  - job_name: 'grafana'
    metrics_path: /metrics
    static_configs:
      - targets: ['grafana:3000']
        labels:
          group: 'grafana'

  - job_name: 'psql'
    metrics_path: /metrics
    static_configs:
      - targets: ['postgresexporter:9187']
        labels:
          group: 'psql'




remote_write:
  - url: "http://promscale:9201/write"
remote_read:
  - url: "http://promscale:9201/read"
    read_recent: true