global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9100']
        labels:
          group: 'linux'

  - job_name: 'containers'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9104']
        labels:
          group: 'docker'

  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8080']
        labels:
          group: 'cadvisor'
