global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prom'
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          group: 'prom'

  - job_name: 'grafana'
    metrics_path: /metrics
    static_configs:
      - targets: ['example_grafana_1:3000']
        labels:
          group: 'grafana'

  - job_name: 'cortex'
    metrics_path: /metrics
    static_configs:
      - targets: ['example_cortex_1:9009']
        labels:
          group: 'cortex'
