{
 "title": "openapi",
 "tags": [
  "3gpp",
  "http2"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(go_goroutines,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_sum{}[1m]))\n/\nsum(rate(request_duration_seconds_count{}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "95% response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{}[1m])) by (le)) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (process_resident_memory_bytes{})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (process_resident_memory_bytes{}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Go memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sum (go_memstats_sys_bytes{})", "legendFormat": "Sys" },
    {
     "expr": "sum (go_memstats_heap_inuse_bytes{})",
     "legendFormat": "HeapInUse"
    },
    {
     "expr": "sum (go_memstats_heap_idle_bytes{})",
     "legendFormat": "HeapIdle"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(go_goroutines{})", "legendFormat": "Goroutines" },
    { "expr": "sum(go_threads{})", "legendFormat": "Threads" }
   ]
  }
 ]
}