# Set global options
data_dir = "/var/lib/vector"

# Vector's API (disabled by default)
# Enable and try it out with the `vector top` command
[api]
enabled = false
# address = "127.0.0.1:8686"

# Ingest data by tailing one or more files
[sources.my_source_id]
type = "docker_logs"
docker_host = "http://dockersock:1234"
include_containers = [ "include_" ]
include_labels = [ "com.example.vendor=Timber Inc." ]
include_images = [ "httpd" ]


# Send structured data to a short-term storage
[sinks.es_cluster]
inputs       = ["my_source_id"]            # only take sampled data
type         = "elasticsearch"
host         = "http://elasticsearch:9200"   # local or external host
index        = "vector-%Y-%m-%d"             # daily indices
