# Set global options
data_dir = "/var/lib/vector"

# Vector's API (disabled by default)
# Enable and try it out with the `vector top` command
[api]
enabled = false
# address = "127.0.0.1:8686"

# Ingest data by tailing one or more files
[sources.apache_logs]
type         = "file"
include      = ["/var/log/apache2/*.log"]    # supports globbing
ignore_older = 86400                         # 1 day

# Structure and parse via Timber's Remap Language
[transforms.remap]
inputs       = ["apache_logs"]
type         = "remap"
source       = '''
. = parse_apache_log(.message)
'''

# Sample the data to save on cost
[transforms.apache_sampler]
inputs       = ["apache_parser"]
type         = "sampler"
rate         = 50                            # only keep 50%

# Send structured data to a short-term storage
[sinks.es_cluster]
inputs       = ["apache_sampler"]            # only take sampled data
type         = "elasticsearch"
host         = "http://elasticsearch:9200"   # local or external host
index        = "vector-%Y-%m-%d"             # daily indices

