scrape_configs:
  - job_name: 'federate'
    scrape_interval: 1m

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{__name__=~".*"}'

    static_configs:
      - targets:
        - 'localhost:9090'

tls_server_config:
  # Certificate and key files for server to use to authenticate to client.
  cert_file: /certs/localhost/tls.crt
  key_file: /certs/localhost/tls.key

http_server_config:
  # Enable HTTP/2 support. Note that HTTP/2 is only supported with TLS.
  # This can not be changed on the fly.
  http2: true