scrape_configs:
  - job_name: 'federate'
    scrape_interval: 1m

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{__name__=~".*"}'

    static_configs:
      - targets:
        - 'localhost:9090'