global:
  evaluation_interval: 1m
  scrape_interval: 1m

scrape_configs:
  - job_name: 'federate'
    scrape_interval: 1m

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{__name__=~".*"}'

    static_configs:
      - targets:
        - 'localhost:9090'

remote_read:
  - url: "http://localhost:8086/api/v1/prom/read?db=prometheus"
    remote_timeout: 30s
    read_recent: true
    name: prometheus
