scrape_configs:
  - job_name: 'federate'
    scrape_interval: 1m

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{__name__=~".*"}'

    static_configs:
      - targets:
        - 'localhost:9090'



remote_write:
  - url: "http://localhost:8086/api/v2/write?org=prometheus&bucket=prometheus"

remote_read:
  - url: "http://localhost:8086/api/v2/read?org=prometheus&bucket=prometheus"
