global:
  evaluation_interval: 1m
  scrape_interval: 1m

remote_read:
  - url: "http://localhost:8086/api/v1/prom/read?db=prometheus"
    remote_timeout: 30s
    read_recent: true
    name: prometheus
