global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'prom'

  - job_name: 'grafana'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:3000']
        labels:
          group: 'grafana'



remote_write:
  - url: "http://localhost:9201/write"
remote_read:
  - url: "http://localhost:9201/read"
    read_recent: true